model_provider = "openrouter"
model_reasoning_effort = "high"
model = "nvidia/nemotron-3-super-120b-a12b:free"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"

[model_providers.mistral]
name = "Mistral"
base_url = "https://api.mistral.ai/v1"
env_key = "MISTRAL_API_KEY"

[features]
shell_snapshot = true # Speed up repeated commands
