# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-150fee35-912f-4aed-adee-bfea9571d38e";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-150fee35-912f-4aed-adee-bfea9571d38e".device =
    "/dev/disk/by-uuid/150fee35-912f-4aed-adee-bfea9571d38e";
  boot.initrd.luks.devices."luks-4aba3580-cf82-4b77-b7bc-a396118939ad".device =
    "/dev/disk/by-uuid/4aba3580-cf82-4b77-b7bc-a396118939ad";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/45E6-8028";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-4aba3580-cf82-4b77-b7bc-a396118939ad"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
