name: GitHub Agentic Workflows Upgrade
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths:
      - .github/workflows/**/*.md
      - .github/workflows/*.md
permissions:
  contents: write
jobs:
  upgrade:
    name: Upgrade
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install GH AW CLI
        uses: github/gh-aw-actions/setup-cli@b078ca291c0c4d3f7bfb88b0f9a01dfb718671e3 # v0.85.1
      - name: Upgrade
        run: gh aw upgrade
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "gh-aw: Upgrade"
          commit_options: --no-verify
          push_options: --force
          file_pattern: .github/
